[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-xml = { version = "0.31", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
